name: Continuous Integration

on:
  push:
    branches: [ master, WIP ]
  pull_request:
    branches: [ master, WIP ]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint + Fix with eslint
        run: npx eslint ./ --fix